### ISSUE TITLE
interfaces/camera error

### ISSUE THREAD

**Issue by sbwml** [DotOS/android_hardware_interfaces#1]
/home/dotOS-o/out/soong/.bootstrap/bin/soong_build  -t -b /home/dotOS-o/out/soong -d /home/dotOS-o/out/soong/build.ninja.d -o /home/dotOS-o/out/soong/build.ninja Android.bp
error: hardware/interfaces/camera/device/1.0/default/Android.bp:36:12: unrecognized property "product_variables.Dot"
error: hardware/interfaces/camera/provider/2.4/default/Android.bp:29:35: unrecognized property "product_variables.dot.uses_qti_camera_device"
error: hardware/interfaces/camera/provider/2.4/default/Android.bp:62:35: unrecognized property "product_variables.dot.uses_qti_camera_device"
[55/55] soong_build docs /home/dotOS-o/out/soong/.bootstrap/docs/soong_build.html
FAILED: /home/dotOS-o/out/soong/.bootstrap/docs/soong_build.html 
/home/dotOS-o/out/soong/.bootstrap/bin/soong_build  -t -b /home/dotOS-o/out/soong --docs /home/dotOS-o/out/soong/.bootstrap/docs/soong_build.html ./Android.bp
error: hardware/interfaces/camera/device/1.0/default/Android.bp:36:12: unrecognized property "product_variables.Dot"
error: hardware/interfaces/camera/provider/2.4/default/Android.bp:29:35: unrecognized property "product_variables.dot.uses_qti_camera_device"
error: hardware/interfaces/camera/provider/2.4/default/Android.bp:62:35: unrecognized property "product_variables.dot.uses_qti_camera_device"
ninja: build stopped: subcommand failed.
15:13:46 soong failed with: exit status 1

#### failed to build some targets (20 seconds) ####

**Comment by mohancm** [comment]
force sync and compile

**Comment by sbwml** [comment]
![image](https://user-images.githubusercontent.com/16485166/37873201-c7cab450-3049-11e8-8f70-9bf0a847f27d.png)

force sync still appear this error.
